# Generated by Django 5.0.6 on 2024-07-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_alter_watchlist_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
